import { jsPDF } from "jspdf";

export default function downloadReport(analysis) {
  const doc = new jsPDF();

  let y = 20;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("Nexora AI Resume Analysis Report", 20, y);

  y += 15;

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");

  doc.text(`Resume Score: ${analysis.resumeScore}%`, 20, y);
  y += 10;

  doc.text(`ATS Score: ${analysis.atsScore}%`, 20, y);
  y += 10;

  doc.text(`Career Match: ${analysis.careerMatch}`, 20, y);
  y += 10;

  doc.text("Career Reason:", 20, y);
  y += 8;

  const reason = doc.splitTextToSize(analysis.careerReason, 170);
  doc.text(reason, 20, y);
  y += reason.length * 7 + 8;

  doc.setFont("helvetica", "bold");
  doc.text("Strengths", 20, y);
  y += 8;

  doc.setFont("helvetica", "normal");

  analysis.strengths.forEach((item) => {
    doc.text(`• ${item}`, 25, y);
    y += 7;
  });

  y += 5;

  doc.setFont("helvetica", "bold");
  doc.text("Missing Skills", 20, y);
  y += 8;

  doc.setFont("helvetica", "normal");

  analysis.missingSkills.forEach((item) => {
    doc.text(`• ${item}`, 25, y);
    y += 7;
  });

  y += 5;

  doc.setFont("helvetica", "bold");
  doc.text("AI Suggestions", 20, y);
  y += 8;

  doc.setFont("helvetica", "normal");

  analysis.suggestions.forEach((item) => {
    doc.text(`• ${item}`, 25, y);
    y += 7;
  });

  y += 15;

  doc.setFont("helvetica", "italic");
  doc.text("Generated by Nexora AI", 20, y);

  doc.save("Nexora_AI_Report.pdf");
}